### ISSUE TITLE
About polyfield

### ISSUE THREAD

**Issue by CGxyol** [aliernfrog/ensicord#10]
I'm sorry to bother you with this item of yours，
I'm a player from China, and I accidentally learned about the game polyfield some time ago，the delay of playing this game in our country is very high, so I would like to take the liberty to ask, can I ask you for a server, I have experience in the development of minecraft server plug-ins, I want to maintain a good game environment, so I want to build a game server in our country.

Looking forward to your reply!

**Comment by aliernfrog** [comment]
This is for Ensicord related issues only. You can check faq channel in Polyfield Discord server to see how to host a server

**Comment by CGxyol** [comment]
> 

Sorry to bother you on this project on github, really sorry,it s my wrong,I made this inappropriate request without thinking too much in the wrong place,please forgive my rudeness
